#!/usr/bin/env bash
# Commit what hivemind's generate-reference just rewrote, and nothing else.
#
# generate-reference (src/bin/generate_reference.rs in alexknips/hivemind)
# writes exactly these files:
#   website/src/content/docs/reference/mcp-tools.md   the whole file, from mcp::tool_definitions()
#   website/src/content/docs/guides/mcp-setup.md      only the digits of its "N tools" mentions
#   website/src/pages/index.astro                     only the digits of its "N tools" mentions
# It reads reference/cli.md and the "Available tools" table in mcp-setup.md
# but never writes them: those are hand-written and updated at release time.
#
# This script is the guarantee that the regenerate job cannot overwrite
# hand-written text. It refuses to commit when any other file changed (a
# future generator that writes more, a stray file) and when either prose file
# changed in any way other than the digits on a line.
#
# Usage, from the site repo root, right after generate-reference:
#   .github/scripts/commit-generated-reference.sh <hivemind-release-tag>
# Writes committed=true|false to $GITHUB_OUTPUT when set. Never pushes.
set -euo pipefail

tag=${1:?usage: $0 <hivemind-release-tag>}

generated=website/src/content/docs/reference/mcp-tools.md
digits_only=(
  website/src/content/docs/guides/mcp-setup.md
  website/src/pages/index.astro
)
allowed=("$generated" "${digits_only[@]}")

# 1. Every changed or untracked path must be one the generator owns.
changed=$(git status --porcelain=v1 --untracked-files=all | cut -c4-)
for path in $changed; do
  ok=false
  for a in "${allowed[@]}"; do [ "$path" = "$a" ] && ok=true; done
  if [ "$ok" = false ]; then
    echo "REFUSING to commit: '$path' changed, and the generator does not own it." >&2
    echo "Changed paths:" >&2
    printf '  %s\n' $changed >&2
    exit 1
  fi
done

# 2. The prose files may differ only in the digits of a line, the way the
#    generator fixes a "27 tools" mention to "28 tools".
for path in "${digits_only[@]}"; do
  if ! git diff -U0 -- "$path" | python3 -c '
import re, sys
minus, plus, in_hunk = [], [], False
for line in sys.stdin:
    if line.startswith("@@"):
        in_hunk = True
        continue
    if not in_hunk or line.startswith("\\"):
        continue
    if line.startswith("-"):
        minus.append(line[1:])
    elif line.startswith("+"):
        plus.append(line[1:])
digits = lambda s: re.sub(r"[0-9]+", "#", s)
same_shape = len(minus) == len(plus) and all(digits(a) == digits(b) for a, b in zip(minus, plus))
sys.exit(0 if same_shape else 1)
'; then
    echo "REFUSING to commit: '$path' changed beyond the digits of its tool-count mentions:" >&2
    git --no-pager diff -- "$path" >&2
    exit 1
  fi
done

committed=false
if [ -z "$changed" ]; then
  echo "No changes: the reference already matches hivemind $tag."
else
  echo "Regenerated from hivemind $tag; committing:"
  git --no-pager diff --stat
  git config user.name "github-actions[bot]"
  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
  git add -- "${allowed[@]}"
  git commit -q \
    -m "docs(reference): regenerate from hivemind $tag" \
    -m "Generated by hivemind's generate-reference at the $tag release tag (the latest release) by the regenerate-reference workflow. The hand-written parts (reference/cli.md, the Available tools table in guides/mcp-setup.md) are untouched by design."
  git --no-pager log -1 --format='%h %s'
  committed=true
fi

if [ -n "${GITHUB_OUTPUT:-}" ]; then
  echo "committed=$committed" >> "$GITHUB_OUTPUT"
fi
if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
  if [ "$committed" = true ]; then
    echo "Regenerated the reference from hivemind **$tag** and committed it." >> "$GITHUB_STEP_SUMMARY"
  else
    echo "The reference already matches hivemind **$tag**; nothing to commit." >> "$GITHUB_STEP_SUMMARY"
  fi
fi
